### ISSUE TITLE
Clearance on PhoenixContact_MSTB-GF_03x5.00mm_Angled_ThreadedFlange_MountHole

### ISSUE THREAD

**Issue by Detzi88** [KiCad/Connectors_Phoenix.pretty#47]
Hi there,
i noticed that the clearance from pad to pad of the above named Connector is 2.8mm. 
Is it possibel to change that to 3mm, so it would meet the reinforced insulation rating according to DIN-EN-61010?
Thanks in foreward

**Comment by SchrodingersGat** [comment]
@poeschlr you made these ones right? Care to comment?

**Comment by poeschlr** [comment]
@Detzi88 
Could you give more details about this rating? (I don't have access to the standard.)

What clearance is necessary to reach the following specifications. (From the technical details page of the connector) It does not make sense for the footprint to reach higher specifications than the connector itself.
Rated voltage (III/3) 	250 V
Rated voltage (III/2) 	320 V
Rated voltage (II/2) 	        400 V

The reason why i ask is, I'm not sure if we should further reduce the annular ring of the pads. (Currently 0.35mm) If we currently do not reach the specifications of the connector than we need to look into it further.

**Comment by Detzi88** [comment]
@poeschlr 

Rated voltage (III/3) 250 V  ->1,5mm 
Rated voltage (III/2) 320 V  ->3mm
Rated voltage (II/2) 400 V   ->3mm

Of course this values can increase depending on the enviroment and materials. They are only the base reference for mains voltage.
I couldn't find an open english reference but if you are keen, or understand german, you could have a look into:
[VDE-IEC](http://www.weidmueller.de/bausteine.net/f/9693/Bemessung_Luft-undKriechstrecken_VDE-IEC.pdf?fd=3)
On Site 1 in "Tabelle 2" is on the left given the surge voltage in kV. Above ratings all specifie 4kV which result in 3mm clearance. I honestly do not know what is meant with "Fall A" and "Fall B" (Fall=Case) because i am not familiar with this standard, but it seems that anything not Case A has to go to special testing.

**Comment by poeschlr** [comment]
I'm a native german speaker. So the link you provided helped a lot.

I made a quick sketch in freecad and found that we currently have a pad to pad clearance of 2.9 mm (not 2.8mm as you wrote.)
Which means i do not need to reduce the pad width by 0.2mm but only by 0.1mm (reduces annular ring to 0.3mm not 0.25mm as i first feared.)

I will add a parameter for min pad to pad clearance to my scripts and regenerate all my connectors with the settings listed below. This way one can generate footprints with different pad to pad clearances if one desires. (Most connectors are already ok. The only problematic connectors are the 5mm and 5.08mm pin pitch connectors.)
- MSTB (320V/4kV) -> 3mm spacing
- GMSTB (630V/6kV) -> 5.5mm spacing
- MC (160V/2.5kV) -> 1.5mm spacing
- MC high voltage (320V/4kV) -> 3mm spacing

**Comment by poeschlr** [comment]
Fix committed.

The MSTB 5.00 and 5.08 series connectors had problems as well as the GMSTB 7.5 series connectors.

**Comment by Detzi88** [comment]
Thank you very much for your effort.

**Comment by poeschlr** [comment]
The fix has been merged. If you are satisfied with the result please close this issue.
